#theme: jekyll-theme-leap-day
#theme: jekyll-theme-hacker
#remote-theme: mmistakes/minimal-mistakes
#remote_theme: hydecorp/hydejack
#remote_theme: DigitalMindCH/twister-jekyll-theme
#remote_theme: mmistakes/jekyll-theme-basically-basic
remote_theme: Liberxue/liberxue.github.io